### ISSUE TITLE
Call Hierarchy not respecting signature

### ISSUE THREAD

**Issue by RobertHeintzCH** [omecra/de.omecra.oedt.updatesite#138] opened 2022-06-28 11:40 UTC
Given this code,
    METHOD PUBLIC VOID TwoParms ( p1 AS CHARACTER, p2 AS CHARACTER ):
    END METHOD.
    METHOD PUBLIC VOID TwoParms ( p1 AS CHARACTER, p2 AS DECIMAL  ):
    END METHOD.
    METHOD PUBLIC VOID Try (  ):
        TwoParms('a', 'b').
        TwoParms('a', 1.5).
    END METHOD.

... positioning the cursor on either of the 2 overloads of "TwoParms" and pressing F4 shows to same: Both calls in "Try".
It should only show the calls with the matching signature - in this case one for each of the 2 overloads.

**Comment by lneumeier** [comment] 2022-08-23 15:24
Duplicate of #99

**Closed** 2022-08-23 15:23 UTC
Labels: duplicate
