### ISSUE TITLE
Enable Preprocessing 

### ISSUE THREAD

**Issue by dredre93** [omecra/de.omecra.oedt.updatesite#176] opened 2023-12-18 12:32 UTC
I noticed that with Progress DeveloperStudio 4.5.2 with OpenEdge Release 11.7.17 and OEDT Plugin Version 9.3.7 the default OpenEdge configuration "Enable Preprocessing" has no effect in OEDT Plugin. 
Is it possible to add kind of inheritance of this setting for the OEDT Plugin? Or how to enable this feature in OEDT?
Consequence is that f.e. using nested include files have no auto completion in case of Temp-Tables .  So Fields in example won't be shown in editor. 

Given Example:
**tt1.i** 
DEFINE TEMP-TABLE tt1 NO-UNDO
  FIELD tt1_id        AS CHARACTER FORMAT "X(64)"
  {tt1fields.i}
  INDEX id IS PRIMARY UNIQUE tt1_id.

**tt1fields.i**
  FIELD tt1_field1        AS CHARACTER FORMAT "X(64)"
  FIELD tt1_field2       AS CHARACTER FORMAT "X(64)"
  FIELD tt1_field3        AS CHARACTER FORMAT "X(64)"

**Comment by lneumeier** [comment] 2024-01-21 14:13
Duplicate of #116

**Closed** 2024-01-21 14:13 UTC
