### ISSUE TITLE
Eclipse momentarily freezing while typing in OEDT editor - no problem in OpenEdge editor

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#183] opened 2024-05-07 13:40 UTC
Hi,

Just noticed since upgrading to 9.5.1, but I recall seeing this before.
When typing in the OEDT editor, the screen momentarily freezes every couple seconds for a short amount of time.
Opening the same file in the OpenEdge editor does not exhibit this behavior.
Any idea what might be causing this?
Below an example, in this case I'm just holding the A key on the keyboard. Notice the jerky output.

![OEDT editor](https://github.com/omecra/de.omecra.oedt.updatesite/assets/8639525/016578f7-b22e-47da-8eb5-210b0e729aea)

The same works fine in the OpenEdge editor...

**Comment by LievenDeFoor** [comment] 2024-05-07 13:50
It seems the problem went away by increasing -Xmx from 256m to 512m.
I'm waiting for some feedback before closing this one again...

**Comment by lneumeier** [comment] 2024-05-07 15:19
It looks like a GC-pause ("Show Heap status" might provide more inside), but I look into it.

**Comment by ccecvb** [comment] 2024-08-08 06:04
@LievenDeFoor I saw the same behaviour, in our case it was related to **Automatically check syntax** turning this of fixed it for me.

![image](https://github.com/user-attachments/assets/4d67c9a5-39b9-4a3b-b757-a303693c8536)

**Comment by lneumeier** [comment] 2024-08-12 17:02
I haven't had any luck reproducing this issue, even with activating "Automatically check syntax". 

@LievenDeFoor 
Did you experienced this problem again after you raised the Xms value?

**Comment by LievenDeFoor** [comment] 2024-08-13 06:51
> @LievenDeFoor Did you experienced this problem again after you raised the Xms value?
I haven't seen the issue again since increasing the Xms value.

**Comment by lneumeier** [comment] 2024-08-14 16:53
Okay, then I'm closing this for now.

**Closed by lneumeier** 2024-08-14 16:53 UTC
Labels: needs investigation
