### ISSUE TITLE
Variable with name "method" incorrectly flagged as unused

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#143] opened 2022-08-23 10:26 UTC
![afbeelding](https://user-images.githubusercontent.com/8639525/186135516-43e071ac-125c-48ac-9980-f3a47c793c6f.png)

Idem for "Class" and perhaps some other keywords used as variable names.

**Comment by LievenDeFoor** [comment] 2022-08-23 10:28
Idem for "Class" and perhaps some other keywords used as variable names.

**Comment by lneumeier** [comment] 2022-11-14 20:21
Duplicate of #146

**Closed** 2022-11-14 20:20 UTC
